import Link from "next/link";
import { ArrowUpRight, CircleCheck, Database, Globe2 } from "lucide-react";
import { HeroSearch } from "@/components/features/HeroSearch";
import { TopNavBar } from "@/components/ui/TopNavBar";
import { getRankings } from "@/lib/data/get-rankings";
import { formatVnd } from "@/lib/utils";

export default async function HomePage() {
  const stocks = (await getRankings()).slice(0, 6);
  return <><TopNavBar/><main className="min-h-screen bg-canvas pb-16 pt-18">
    <section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-14 md:py-20"><p className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600"><CircleCheck size={14} className="text-bull"/>HOSE · HNX · UPCOM</p><h1 className="mt-6 max-w-4xl text-balance text-4xl font-bold leading-tight tracking-[-0.035em] text-navy md:text-6xl">Hiểu doanh nghiệp trước khi quyết định đầu tư.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-600">Tìm một mã cổ phiếu để xem báo cáo tài chính theo quý, tín hiệu kỹ thuật và phân tích AI có dẫn nguồn internet tại thời điểm tìm kiếm.</p><HeroSearch/><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><span className="inline-flex items-center gap-1.5"><Database size={14}/>Dữ liệu thị trường đã đồng bộ</span><span className="inline-flex items-center gap-1.5"><Globe2 size={14}/>Nguồn web realtime</span><span>Không phải khuyến nghị đầu tư</span></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-xl font-bold text-navy">Mã đang có dữ liệu thị trường</h2><p className="mt-1 text-sm text-slate-600">Chọn nhanh để mở dashboard phân tích.</p></div><Link href="/discover" className="inline-flex items-center gap-1.5 text-sm font-semibold text-blue-800 hover:underline">Xem tất cả<ArrowUpRight size={15}/></Link></div>{stocks.length > 0 ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{stocks.map((stock) => <Link key={stock.symbol} href={`/analysis/${stock.symbol}`} className="panel flex items-center justify-between p-4 transition hover:border-slate-400 hover:shadow-md"><div><p className="font-mono text-sm font-bold text-navy">{stock.symbol}</p><p className="mt-1 line-clamp-1 text-xs text-slate-500">{stock.company}</p></div><div className="text-right"><p className="font-mono text-sm font-semibold">{formatVnd(stock.price)}</p><p className={`mt-1 font-mono text-xs font-semibold ${stock.change >= 0 ? "text-bull" : "text-bear"}`}>{stock.change >= 0 ? "+" : ""}{stock.change}%</p></div></Link>)}</div> : <div className="panel mt-5 p-6"><p className="text-sm font-semibold text-navy">Chưa có dữ liệu giá đồng bộ</p><p className="mt-1 text-sm text-slate-600">Bạn vẫn có thể tìm mã trong catalog HOSE, HNX và UPCOM để chạy nghiên cứu AI realtime.</p></div>}</section>
  </main></>;
}
