"use client";
import { useState } from "react";
import Link from "next/link";
import { DisclaimerCard } from "./DisclaimerCard";
import { RatingBadge } from "./RatingBadge";
import type { RankingItem } from "@/types/stock";
import { cn, formatVnd } from "@/lib/utils";
import { WatchlistButton } from "./WatchlistButton";
export function DiscoverClient({items,initialWatchlist=[]}:{items:RankingItem[];initialWatchlist?:string[]}) { const sectors=["Tất cả",...Array.from(new Set(items.map((item)=>item.sector))).sort()]; const [active,setActive]=useState("Tất cả"); const visible=active==="Tất cả"?items:items.filter(i=>i.sector===active); return <><div className="flex gap-2 overflow-x-auto pb-2" aria-label="Lọc cổ phiếu theo ngành">{sectors.map(s=><button key={s} onClick={()=>setActive(s)} aria-pressed={active===s} className={cn("shrink-0 rounded-lg border px-3 py-2 text-xs font-semibold",active===s?"border-navy bg-navy text-white":"border-slate-300 bg-white text-slate-700 hover:bg-slate-50")}>{s}</button>)}</div><section className="panel mt-4 overflow-hidden"><div className="panel-header"><div><h2 className="font-bold text-navy">Danh sách đồng bộ</h2><p className="mt-1 text-xs text-slate-500">Xếp hạng rule-based từ EMA và dữ liệu OHLCV</p></div><span className="text-xs font-semibold text-slate-500">{visible.length} mã</span></div><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left"><thead className="border-b border-slate-200 bg-slate-50"><tr>{["Hạng","Doanh nghiệp","Ngành","Giá gần nhất","Thay đổi","Điểm","Tín hiệu","Theo dõi"].map(h=><th key={h} className="label px-4 py-3">{h}</th>)}</tr></thead><tbody>{visible.map(i=><tr key={i.symbol} className="table-row"><td className="px-4 py-4 font-mono text-slate-400">{i.rank}</td><td className="px-4"><Link href={`/analysis/${i.symbol}`} className="font-mono text-sm font-bold text-blue-800 hover:underline">{i.symbol}</Link><p className="text-xs text-slate-500">{i.company}</p></td><td className="px-4 text-xs text-slate-600">{i.sector}</td><td className="data px-4 text-right">{formatVnd(i.price)}</td><td className={`data px-4 text-right ${i.change>=0?"text-bull":"text-bear"}`}>{i.change>=0?"+":""}{i.change}%</td><td className="px-4"><div className="flex items-center gap-2"><span className="data font-semibold">{i.score}</span><span className="h-1.5 w-16 bg-slate-100"><span className="block h-full bg-navy" style={{width:`${i.score}%`}}/></span></div></td><td className="px-4"><RatingBadge rating={i.rating}/></td><td className="px-4"><WatchlistButton symbol={i.symbol} initiallySaved={initialWatchlist.includes(i.symbol)}/></td></tr>)}</tbody></table>{visible.length===0&&<div className="p-8 text-center"><p className="text-sm font-semibold text-navy">Không có mã phù hợp</p><button onClick={()=>setActive("Tất cả")} className="mt-3 text-sm font-semibold text-blue-800 underline underline-offset-4">Hiện tất cả</button></div>}</div></section><div className="mt-5"><DisclaimerCard/></div></>; }
