"use client";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Eye, EyeOff, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export function LoginForm() {
  const [email,setEmail] = useState(""); const [password,setPassword] = useState(""); const [show,setShow] = useState(false); const [error,setError] = useState(""); const [loading,setLoading] = useState(false);
  const router = useRouter(); const params = useSearchParams(); const next = params.get("next") || "/home";
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(""); try { const supabase = createClient(); const { error: authError } = await supabase.auth.signInWithPassword({email,password}); if (authError) throw authError; router.replace(next); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to sign in. Check your credentials and try again."); } finally { setLoading(false); } }
  async function google() { setLoading(true); setError(""); try { const supabase = createClient(); const { error: authError } = await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/auth/callback?next=${encodeURIComponent(next)}`}}); if (authError) throw authError; } catch (err) { setError(err instanceof Error ? err.message : "Google sign-in could not start."); setLoading(false); } }
  return <form onSubmit={submit} className="space-y-5"><button type="button" onClick={google} disabled={loading} className="btn-secondary w-full"><span className="font-bold text-blue-600">G</span>Continue with Google</button><div className="flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200"/>or continue with email<span className="h-px flex-1 bg-slate-200"/></div><label className="block"><span className="label">Email address</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 h-11 w-full rounded border border-slate-200 px-3 text-sm outline-none focus:border-slate-500" placeholder="you@company.com"/></label><label className="block"><span className="label">Password</span><span className="relative mt-2 block"><input required minLength={6} type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} className="h-11 w-full rounded border border-slate-200 px-3 pr-11 text-sm outline-none focus:border-slate-500" placeholder="Enter your password"/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?"Hide password":"Show password"} className="absolute right-0 top-0 grid size-11 place-items-center text-slate-400">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label>{error && <p role="alert" className="rounded bg-red-50 px-3 py-2 text-xs leading-5 text-red-700">{error}</p>}<div className="flex items-center justify-between text-xs"><label className="flex items-center gap-2 text-slate-600"><input type="checkbox"/>Remember me</label><button type="button" className="font-semibold text-navy underline-offset-4 hover:underline">Forgot password?</button></div><button disabled={loading} className="btn-primary h-11 w-full">{loading?<><Loader2 size={16} className="animate-spin"/>Signing in…</>:"Sign in to research"}</button></form>;
}
