"use client";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Eye, EyeOff, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export function LoginForm() {
  const [email,setEmail] = useState(""); const [password,setPassword] = useState(""); const [show,setShow] = useState(false); const [error,setError] = useState(""); const [loading,setLoading] = useState(false);
  const router = useRouter(); const params = useSearchParams(); const next = params.get("next") || "/home";
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(""); try { const supabase = createClient(); const { error: authError } = await supabase.auth.signInWithPassword({email,password}); if (authError) throw authError; router.replace(next); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to sign in. Check your credentials and try again."); } finally { setLoading(false); } }
  async function google() { setLoading(true); setError(""); try { const supabase = createClient(); const { error: authError } = await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/auth/callback?next=${encodeURIComponent(next)}`}}); if (authError) throw authError; } catch (err) { setError(err instanceof Error ? err.message : "Google sign-in could not start."); setLoading(false); } }
  return <form onSubmit={submit} className="space-y-5"><button type="button" onClick={google} disabled={loading} className="btn-secondary h-11 w-full"><span className="font-bold text-blue-700">G</span>Tiếp tục với Google</button><div className="flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200"/>hoặc dùng email<span className="h-px flex-1 bg-slate-200"/></div><label className="block"><span className="text-sm font-semibold text-slate-700">Email</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 h-11 w-full rounded-lg border border-slate-300 px-3 text-sm outline-none focus:border-navy" placeholder="ban@example.com"/></label><label className="block"><span className="text-sm font-semibold text-slate-700">Mật khẩu</span><span className="relative mt-2 block"><input required minLength={6} type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} className="h-11 w-full rounded-lg border border-slate-300 px-3 pr-11 text-sm outline-none focus:border-navy" placeholder="Nhập mật khẩu"/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?"Ẩn mật khẩu":"Hiện mật khẩu"} className="absolute right-0 top-0 grid size-11 place-items-center text-slate-500">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label>{error && <p role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-xs leading-5 text-red-700">{error}</p>}<button disabled={loading} className="btn-primary h-11 w-full">{loading?<><Loader2 size={16} className="animate-spin"/>Đang đăng nhập…</>:"Đăng nhập để nghiên cứu"}</button></form>;
}
