import { ArrowDownRight, ArrowUpRight, BrainCircuit } from "lucide-react";
import { getNews } from "@/lib/data/get-news";
import { getRankings } from "@/lib/data/get-rankings";
import { formatVnd } from "@/lib/utils";
import { MarketChart } from "./MarketChart";
import { MarketOverviewBar } from "./MarketOverviewBar";

export async function MarketDashboard() {
  const [movers, news] = await Promise.all([getRankings(), getNews()]);
  return <div><MarketOverviewBar/><div className="p-4 md:p-6"><div className="mb-6"><h1 className="font-display text-display font-semibold tracking-tight">Market overview</h1><p className="mt-1 text-sm text-slate-500">Vietnam equities · Wednesday, 26 August</p></div><div className="grid gap-4 xl:grid-cols-[1.5fr_.8fr]"><section className="panel"><div className="panel-header"><div><p className="label">Market performance</p><h2 className="mt-1 font-display text-title font-semibold">VN-Index intraday</h2></div><span className="data text-bull">+7.91 · +0.62%</span></div><div className="p-4"><MarketChart/></div></section><section className="panel"><div className="panel-header"><h2 className="font-display font-semibold">Top movers</h2><button className="text-xs font-semibold text-slate-500">View all</button></div><div>{movers.slice(0,5).map(item=><div key={item.symbol} className="table-row flex items-center justify-between px-5 py-3"><div><p className="font-mono text-sm font-semibold">{item.symbol}</p><p className="text-xs text-slate-500">{item.company}</p></div><div className="text-right"><p className="data">{formatVnd(item.price)}</p><p className={`data text-xs ${item.change>=0?"text-bull":"text-bear"}`}>{item.change>=0?"+":""}{item.change}%</p></div></div>)}</div></section></div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1fr]"><section className="panel"><div className="panel-header"><div className="flex items-center gap-2"><BrainCircuit size={18}/><h2 className="font-display font-semibold">AI insights</h2></div><span className="label">Synthetic</span></div><div className="divide-y divide-slate-100">{news.map(n=><article key={n.id} className="p-5"><div className="flex items-center gap-2 text-xs text-slate-400"><span>{n.source}</span><span>·</span><span>{n.publishedAt}</span></div><h3 className="mt-2 font-display text-sm font-semibold">{n.headline}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{n.summary}</p></article>)}</div></section><section className="panel"><div className="panel-header"><h2 className="font-display font-semibold">Market breadth</h2><span className="data text-bull">Healthy</span></div><div className="grid grid-cols-3 gap-px bg-slate-200"><div className="bg-white p-5"><ArrowUpRight className="text-bull"/><p className="mt-5 data text-2xl font-semibold">214</p><p className="label mt-1">Advancing</p></div><div className="bg-white p-5"><ArrowDownRight className="text-bear"/><p className="mt-5 data text-2xl font-semibold">137</p><p className="label mt-1">Declining</p></div><div className="bg-white p-5"><span className="block h-5 w-5 border-t-2 border-slate-400"/><p className="mt-5 data text-2xl font-semibold">61</p><p className="label mt-1">Unchanged</p></div></div></section></div></div></div>;
}
